# Generated by Django 3.1.4 on 2020-12-19 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('serial', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('type1', models.CharField(max_length=100)),
                ('type2', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
