# Generated by Django 3.1.4 on 2020-12-19 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokeapi', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pokemon',
        ),
    ]
