# Generated by Django 3.1.4 on 2020-12-20 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pokeapi', '0002_delete_pokemon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('code', models.IntegerField()),
                ('serial', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('type1', models.CharField(max_length=100)),
                ('type2', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('ability1', models.CharField(max_length=100)),
                ('ability2', models.CharField(max_length=100)),
                ('hidden_ability', models.CharField(max_length=100)),
                ('generation', models.IntegerField()),
                ('legendary', models.BooleanField()),
                ('mega_evolution', models.BooleanField()),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('hp', models.IntegerField()),
                ('attack', models.IntegerField()),
                ('defense', models.IntegerField()),
                ('special_attack', models.IntegerField()),
                ('special_defense', models.IntegerField()),
                ('speed', models.IntegerField()),
                ('total', models.IntegerField()),
            ],
        ),
    ]
