# Generated by Django 3.1.4 on 2020-12-20 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokeapi', '0003_pokemon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='legendary',
            field=models.BooleanField(default=True),
        ),
    ]
