# Generated by Django 3.1.4 on 2020-12-20 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokeapi', '0004_auto_20201220_0225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='legendary',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='mega_evolution',
            field=models.IntegerField(),
        ),
    ]
